namespace BunnyTail.EmbeddedBuildProperty.Generator;

using System;
using System.Collections.Generic;
using System.Text;

using BunnyTail.EmbeddedBuildProperty.Generator.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

using SourceGenerateHelper;

[Generator]
public sealed class BuildPropertyGenerator : IIncrementalGenerator
{
    // ------------------------------------------------------------
    // Initialize
    // ------------------------------------------------------------

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var model = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) =>
        {
            provider.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
            provider.GlobalOptions.TryGetValue("build_property.EmbeddedPropertyClass", out var className);
            provider.GlobalOptions.TryGetValue("build_property._EmbeddedPropertyValues", out var values);

            return new BuildPropertyModel(
                ns ?? string.Empty,
                String.IsNullOrEmpty(className) ? "EmbeddedProperty" : className!,
                values ?? string.Empty);
        });

        context.RegisterSourceOutput(
            model,
            Execute);
    }

    // ------------------------------------------------------------
    // Generator
    // ------------------------------------------------------------

    private static void Execute(SourceProductionContext context, BuildPropertyModel model)
    {
        if (String.IsNullOrEmpty(model.Values))
        {
            return;
        }

        if (!String.IsNullOrEmpty(model.Namespace) && !IsValidNamespace(model.Namespace))
        {
            context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.InvalidNamespace, (Location?)null, model.Namespace));
            return;
        }

        if (!IsValidName(model.ClassName))
        {
            context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.InvalidClassName, (Location?)null, model.ClassName));
            return;
        }

        var builder = new SourceBuilder();

        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        // namespace
        if (!String.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        // class
        builder
            .Indent()
            .Append("internal static partial class ")
            .Append(model.ClassName)
            .NewLine();
        builder.BeginScope();

        var span = model.Values.AsSpan().Trim();
        var names = new HashSet<string>(StringComparer.Ordinal);

        var first = true;
        while (TryReadSegment(ref span, out var segment))
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            if (String.IsNullOrWhiteSpace(segment))
            {
                continue;
            }

            if (!TryParseEntry(context, segment, out var name, out var type, out var value))
            {
                continue;
            }

            if (!IsValidName(name))
            {
                context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.InvalidConstName, (Location?)null, name));
                continue;
            }

            if (!IsSupportedType(type))
            {
                context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.UnsupportedConstType, (Location?)null, type, name));
                continue;
            }

            if ((type != "string") && String.IsNullOrEmpty(value))
            {
                context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.EmptyConstValue, (Location?)null, name, type));
                continue;
            }

            if (!names.Add(name))
            {
                context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.DuplicateConstName, (Location?)null, name));
                continue;
            }

            if (first)
            {
                first = false;
            }
            else
            {
                builder.NewLine();
            }

            builder
                .Indent()
                .Append("public const ")
                .Append(type)
                .Append(' ')
                .Append(name)
                .Append(" = ")
                .Append(FormatLiteral(type, value))
                .Append(';')
                .NewLine();
        }

        builder.EndScope();

        var source = builder.ToString();
        context.AddSource("EmbeddedProperty.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    // ------------------------------------------------------------
    // Parse
    // ------------------------------------------------------------

    private static bool TryReadSegment(ref ReadOnlySpan<char> source, out string segment)
    {
        if (source.IsEmpty)
        {
            segment = string.Empty;
            return false;
        }

        using var sb = new ValueStringBuilder(stackalloc char[256]);
        var i = 0;
        while (i < source.Length)
        {
            var c = source[i];
            if (c == '\\')
            {
                if (((i + 1) < source.Length) && (source[i + 1] == ','))
                {
                    sb.Append(',');
                    i += 2;
                    continue;
                }

                sb.Append('\\');
                i++;
                continue;
            }

            if (c == ',')
            {
                i++;
                break;
            }

            sb.Append(c);
            i++;
        }

        source = source.Slice(i).TrimStart();
        segment = sb.ToString();
        return true;
    }

    private static bool TryParseEntry(SourceProductionContext context, string segment, out string name, out string type, out string value)
    {
        name = string.Empty;
        type = string.Empty;
        value = string.Empty;

        var nameEnd = segment.IndexOf('=');
        if (nameEnd <= 0)
        {
            context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.InvalidConstValueName, (Location?)null, segment));
            return false;
        }

        var typeStart = nameEnd + 1;
        var typeEnd = segment.IndexOf(':', typeStart);
        if (typeEnd <= typeStart)
        {
            context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.InvalidConstValueType, (Location?)null, segment));
            return false;
        }

        name = segment.AsSpan(0, nameEnd).Trim().ToString();
        type = segment.AsSpan(typeStart, typeEnd - typeStart).Trim().ToString();
        value = segment.AsSpan(typeEnd + 1).Trim().ToString();
        return true;
    }

    // ------------------------------------------------------------
    // Validate
    // ------------------------------------------------------------

    private static bool IsValidNamespace(string ns)
    {
        // ReSharper disable once LoopCanBeConvertedToQuery
        foreach (var part in ns.Split('.'))
        {
            if (!IsValidName(part))
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsValidName(string name) =>
        SyntaxFacts.IsValidIdentifier(name) && (SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None);

    private static bool IsSupportedType(string type) => type switch
    {
        "string" or "bool" or "char" or
        "byte" or "sbyte" or "short" or "ushort" or
        "int" or "uint" or "long" or "ulong" or
        "float" or "double" or "decimal" => true,
        _ => false
    };

    // ------------------------------------------------------------
    // Literal
    // ------------------------------------------------------------

    private static string FormatLiteral(string type, string value) => type switch
    {
        "string" => $"@\"{value.Replace("\"", "\"\"")}\"",
        "char" => $"'{value.Replace("\\", "\\\\").Replace("'", "\\'")}'",
        "float" => HasSuffix(value, 'f', 'F') ? value : value + "f",
        "decimal" => HasSuffix(value, 'm', 'M') ? value : value + "m",
        _ => value
    };

    private static bool HasSuffix(string value, char lower, char upper)
    {
        if (value.Length == 0)
        {
            return false;
        }

        var last = value[value.Length - 1];
        return (last == lower) || (last == upper);
    }
}
