namespace BunnyTail.EmbeddedBuildProperty.Generator;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

using BunnyTail.EmbeddedBuildProperty.Generator.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

using SourceGenerateHelper;

[Generator]
public sealed class BuildPropertyGenerator : IIncrementalGenerator
{
    // ------------------------------------------------------------
    // Initialize
    // ------------------------------------------------------------

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var model = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) =>
        {
            provider.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
            provider.GlobalOptions.TryGetValue("build_property.EmbeddedPropertyClass", out var className);
            provider.GlobalOptions.TryGetValue("build_property._EmbeddedPropertyValues", out var values);

            return new BuildPropertyModel(
                ns ?? string.Empty,
                String.IsNullOrEmpty(className) ? "EmbeddedProperty" : className!,
                values ?? string.Empty);
        });

        context.RegisterSourceOutput(
            model,
            Execute);
    }

    // ------------------------------------------------------------
    // Generator
    // ------------------------------------------------------------

    private static void Execute(SourceProductionContext context, BuildPropertyModel model)
    {
        if (String.IsNullOrEmpty(model.Values))
        {
            return;
        }

        if (!String.IsNullOrEmpty(model.Namespace) && !IsValidNamespace(model.Namespace))
        {
            context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.InvalidNamespace, (Location?)null, model.Namespace));
            return;
        }

        if (!IsValidName(model.ClassName))
        {
            context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.InvalidClassName, (Location?)null, model.ClassName));
            return;
        }

        var builder = new SourceBuilder();

        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        // namespace
        if (!String.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        // class
        builder
            .Indent()
            .Append("internal static partial class ")
            .Append(model.ClassName)
            .NewLine();
        builder.BeginScope();

        var span = model.Values.AsSpan().Trim();
        var names = new HashSet<string>(StringComparer.Ordinal);

        var first = true;
        while (TryReadSegment(ref span, out var segment))
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            if (String.IsNullOrWhiteSpace(segment))
            {
                continue;
            }

            if (!TryParseEntry(context, segment, out var name, out var type, out var value))
            {
                continue;
            }

            if (!IsValidName(name))
            {
                context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.InvalidConstName, (Location?)null, name));
                continue;
            }

            if (!IsSupportedType(type))
            {
                context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.UnsupportedConstType, (Location?)null, type, name));
                continue;
            }

            if ((type != "string") && String.IsNullOrEmpty(value))
            {
                context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.EmptyConstValue, (Location?)null, name, type));
                continue;
            }

            if (!TryFormatLiteral(type, value, out var literal))
            {
                context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.InvalidConstValue, (Location?)null, name, type, value));
                continue;
            }

            if (!names.Add(name))
            {
                context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.DuplicateConstName, (Location?)null, name));
                continue;
            }

            if (first)
            {
                first = false;
            }
            else
            {
                builder.NewLine();
            }

            builder
                .Indent()
                .Append("public const ")
                .Append(type)
                .Append(' ')
                .Append(name)
                .Append(" = ")
                .Append(literal)
                .Append(';')
                .NewLine();
        }

        builder.EndScope();

        var source = builder.ToString();
        context.AddSource("EmbeddedProperty.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    // ------------------------------------------------------------
    // Parser
    // ------------------------------------------------------------

    private static bool TryReadSegment(ref ReadOnlySpan<char> source, out string segment)
    {
        if (source.IsEmpty)
        {
            segment = string.Empty;
            return false;
        }

        using var sb = new ValueStringBuilder(stackalloc char[256]);
        var i = 0;
        while (i < source.Length)
        {
            var c = source[i];
            if (c == '\\')
            {
                if (((i + 1) < source.Length) && (source[i + 1] == ','))
                {
                    sb.Append(',');
                    i += 2;
                    continue;
                }

                sb.Append('\\');
                i++;
                continue;
            }

            if (c == ',')
            {
                i++;
                break;
            }

            sb.Append(c);
            i++;
        }

        source = source.Slice(i).TrimStart();
        segment = sb.ToString();
        return true;
    }

    private static bool TryParseEntry(SourceProductionContext context, string segment, out string name, out string type, out string value)
    {
        name = string.Empty;
        type = string.Empty;
        value = string.Empty;

        var nameEnd = segment.IndexOf('=');
        if (nameEnd <= 0)
        {
            context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.NameSeparatorNotFound, (Location?)null, segment));
            return false;
        }

        var typeStart = nameEnd + 1;
        var typeEnd = segment.IndexOf(':', typeStart);
        if (typeEnd <= typeStart)
        {
            context.ReportDiagnostic(new DiagnosticInfo(Diagnostics.TypeSeparatorNotFound, (Location?)null, segment));
            return false;
        }

        name = segment.AsSpan(0, nameEnd).Trim().ToString();
        type = segment.AsSpan(typeStart, typeEnd - typeStart).Trim().ToString();
        value = segment.AsSpan(typeEnd + 1).Trim().ToString();
        return true;
    }

    // ------------------------------------------------------------
    // Validate
    // ------------------------------------------------------------

    private static bool IsValidNamespace(string ns)
    {
        // ReSharper disable once LoopCanBeConvertedToQuery
        foreach (var part in ns.Split('.'))
        {
            if (!IsValidName(part))
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsValidName(string name) =>
        SyntaxFacts.IsValidIdentifier(name) && (SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None);

    private static bool IsSupportedType(string type) => type switch
    {
        "string" or "bool" or "char" or
        "byte" or "sbyte" or "short" or "ushort" or
        "int" or "uint" or "long" or "ulong" or
        "float" or "double" or "decimal" => true,
        _ => false
    };

    // ------------------------------------------------------------
    // Literal
    // ------------------------------------------------------------

    private static bool TryFormatLiteral(string type, string value, out string literal)
    {
        switch (type)
        {
            case "string":
                literal = $"@\"{value.Replace("\"", "\"\"")}\"";
                return true;
            case "bool":
                if (Boolean.TryParse(value, out var boolValue))
                {
                    literal = boolValue ? "true" : "false";
                    return true;
                }
                break;
            case "char":
                if (value.Length == 1)
                {
                    literal = $"'{Escape(value[0])}'";
                    return true;
                }
                break;
            case "byte":
                if (Byte.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var byteValue))
                {
                    literal = byteValue.ToString(CultureInfo.InvariantCulture);
                    return true;
                }
                break;
            case "sbyte":
                if (SByte.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var sbyteValue))
                {
                    literal = sbyteValue.ToString(CultureInfo.InvariantCulture);
                    return true;
                }
                break;
            case "short":
                if (Int16.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var shortValue))
                {
                    literal = shortValue.ToString(CultureInfo.InvariantCulture);
                    return true;
                }
                break;
            case "ushort":
                if (UInt16.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var ushortValue))
                {
                    literal = ushortValue.ToString(CultureInfo.InvariantCulture);
                    return true;
                }
                break;
            case "int":
                if (Int32.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var intValue))
                {
                    literal = intValue.ToString(CultureInfo.InvariantCulture);
                    return true;
                }
                break;
            case "uint":
                if (UInt32.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var uintValue))
                {
                    literal = uintValue.ToString(CultureInfo.InvariantCulture) + "u";
                    return true;
                }
                break;
            case "long":
                if (Int64.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var longValue))
                {
                    literal = longValue.ToString(CultureInfo.InvariantCulture) + "L";
                    return true;
                }
                break;
            case "ulong":
                if (UInt64.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var ulongValue))
                {
                    literal = ulongValue.ToString(CultureInfo.InvariantCulture) + "UL";
                    return true;
                }
                break;
            case "float":
                return TryFormatFloat(value, out literal);
            case "double":
                return TryFormatDouble(value, out literal);
            case "decimal":
                return TryFormatDecimal(value, out literal);
        }

        literal = string.Empty;
        return false;
    }

    private static bool TryFormatFloat(string value, out string literal)
    {
        var body = TrimSuffix(value, 'f', 'F');
        if (Single.TryParse(body, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed) &&
            !Single.IsNaN(parsed) && !Single.IsInfinity(parsed))
        {
            literal = body + "f";
            return true;
        }

        literal = string.Empty;
        return false;
    }

    private static bool TryFormatDouble(string value, out string literal)
    {
        var body = TrimSuffix(value, 'd', 'D');
        if (Double.TryParse(body, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed) &&
            !Double.IsNaN(parsed) && !Double.IsInfinity(parsed))
        {
            literal = body + "d";
            return true;
        }

        literal = string.Empty;
        return false;
    }

    private static bool TryFormatDecimal(string value, out string literal)
    {
        var body = TrimSuffix(value, 'm', 'M');
        if (Decimal.TryParse(body, NumberStyles.Float, CultureInfo.InvariantCulture, out _))
        {
            literal = body + "m";
            return true;
        }

        literal = string.Empty;
        return false;
    }

    private static string TrimSuffix(string value, char lower, char upper)
    {
        if (value.Length == 0)
        {
            return value;
        }

        var last = value[value.Length - 1];
        return ((last == lower) || (last == upper)) ? value.Substring(0, value.Length - 1) : value;
    }

    private static string Escape(char value) => value switch
    {
        '\'' => "\\'",
        '\\' => "\\\\",
        _ => value.ToString()
    };
}
